export const AvailableDances = [
  { name: "Dance 1", dict: "anim@amb@nightclub@dancers@podium_dancers@", anim: "hi_dance_facedj_17_v2_male^5", duration: 12000000, animFlag: 1 },
  { name: "Dance 2", dict: "anim@amb@casino@mini@dance@dance_solo@female@var_a@", anim: "med_center", duration: 12000000, animFlag: 1 },
  { name: "Dance 3", dict: "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim: "high_center", duration: 12000000, animFlag: 1 },
  { name: "Dance 4", dict: "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim: "high_center", duration: 12000000, animFlag: 1 },
  { name: "Slow", dict: "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim: "low_center", duration: 12000000, animFlag: 1 },
  { name: "Slow 2", dict: "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim: "low_center_down", duration: 12000000, animFlag: 1 },
  { name: "Slow 3", dict: "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim: "low_center", duration: 12000000, animFlag: 1 },
  { name: "Slow 4", dict: "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim: "low_center", duration: 12000000, animFlag: 1 },
  { name: "Slow 5", dict: "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim: "low_center_down", duration: 12000000, animFlag: 1 },
  { name: "Slow 6", dict: "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", anim: "low_center", duration: 12000000, animFlag: 1 },
  { name: "Hands Up", dict: "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim: "med_center_up", duration: 12000000, animFlag: 1 },
  { name: "Hands Up 2", dict: "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim: "high_center_up", duration: 12000000, animFlag: 1 },
  { name: "Hands Up 3", dict: "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim: "high_center_up", duration: 12000000, animFlag: 1 },
  { name: "Hands Up 4", dict: "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", anim: "high_center_up", duration: 12000000, animFlag: 1 },
  { name: "Shake The Hips", dict: "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", anim: "hi_dance_facedj_09_v2_female^1", duration: 12000000, animFlag: 1 },
  { name: "Shake The Hips 2", dict: "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", anim: "hi_dance_facedj_09_v2_female^3", duration: 12000000, animFlag: 1 },
  { name: "Shake The Hips 3", dict: "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim: "high_center", duration: 12000000, animFlag: 1 },
  { name: "Shake The Hips 4", dict: "anim@amb@nightclub@dancers@solomun_entourage@", anim: "mi_dance_facedj_17_v1_female^1", duration: 12000000, animFlag: 1 },
  { name: "Shuffle", dict: "anim@amb@casino@mini@dance@dance_solo@female@var_b@", anim: "high_center", duration: 12000000, animFlag: 1 },
  { name: "Throw Away", dict: "anim@amb@nightclub@lazlow@hi_podium@", anim: "danceidle_hi_11_buttwiggle_b_laz", duration: 12000000, animFlag: 1 },
  { name: "Tao", dict: "misschinese2_crystalmazemcs1_cs", anim: "dance_loop_tao", duration: 12000000, animFlag: 1 },
  { name: "Down Under", dict: "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", anim: "high_center_down", duration: 12000000, animFlag: 1 },
  { name: "Gangster", dict: "missfbi3_sniping", anim: "dance_m_default", duration: 12000000, animFlag: 1 },
  { name: "What is Dance?", dict: "timetable@tracy@ig_5@idle_a", anim: "idle_a", duration: 12000000, animFlag: 1 },
  { name: "The Trout", dict: "anim@mp_player_intupperfind_the_fish", anim: "idle_a", duration: 12000000, animFlag: 1 },
  { name: "Tap Dance", dict: "special_ped@mountain_dancer@monologue_3@monologue_3a", anim: "mnt_dnc_buttwag", duration: 12000000, animFlag: 1 },
  { name: "Unmotivated", dict: "move_clown@p_m_zero_idles@", anim: "fidget_short_dance", duration: 12000000, animFlag: 1 },
  { name: "Clown", dict: "move_clown@p_m_two_idles@", anim: "fidget_short_dance", duration: 12000000, animFlag: 1 },
  { name: "The Mixer", dict: "anim@mp_player_intcelebrationfemale@the_woogie", anim: "the_woogie", duration: 12000000, animFlag: 1 },
  { name: "Just Looking", dict: "timetable@tracy@ig_8@idle_b", anim: "idle_d", duration: 12000000, animFlag: 1 },
  { name: "Striptease", dict: "mini@strip_club@private_dance@idle", anim: "priv_dance_idle", duration: 12000000, animFlag: 1 },
  { name: "Striptease 2", dict: "mini@strip_club@private_dance@part2", anim: "priv_dance_p2", duration: 12000000, animFlag: 1 },
  { name: "Striptease 3", dict: "mini@strip_club@private_dance@part3", anim: "priv_dance_p3", duration: 12000000, animFlag: 1 }
];

export const AvailableWalkstyles = [
  { name: "Normal", anim: "normal" },
  { name: "Injured", anim: "move_m@injured" },
  { name: "Dizzy", anim: "move_m@buzzed" },
  { name: "Gangster", anim: "move_m@gangster@generic" },
  { name: "Gangster 2", anim: "move_m@casual@d" },
  { name: "Tipsy", anim: "move_m@drunk@slightlydrunk" },
  { name: "Drunk", anim: "move_m@drunk@a" },
  { name: "Very Drunk", anim: "move_m@drunk@verydrunk" },
  { name: "Groovy", anim: "anim@move_m@grooving@" },
  { name: "Casual", anim: "move_m@casual@a" },
  { name: "Casual 2", anim: "move_m@casual@e" },
  { name: "Casual 3", anim: "move_m@casual@f" },
  { name: "Sad", anim: "move_m@sad@a" },
  { name: "Feminine", anim: "move_f@sexy@a" },
  { name: "Chichi", anim: "move_f@chichi" }
];
 
export const Surrender = [
  { name: "Hands Up", anim: "handsup_base", duration: 12000000, animFlag: 49, dict: "missminuteman_1ig_2" },
  { name: "Surrender", anim: "idle_a", duration: 12000000, animFlag: 49, dict: "random@arrests@busted" }
];

export const Lay = [
  { name: "Chilling (Lying)", anim: "trev_scares_tramp_idle_tramp", duration: 12000000, animFlag: 1, dict: "switch@trevor@scares_tramp" },
  { name: "Lying", anim: "trev_annoys_sunbathers_loop_girl", duration: 12000000, animFlag: 1, dict: "switch@trevor@annoys_sunbathers" },
  { name: "Lying 2", anim: "trev_annoys_sunbathers_loop_guy", duration: 12000000, animFlag: 1, dict: "switch@trevor@annoys_sunbathers" },
  { name: "Lying 3", anim: "base", duration: 12000000, animFlag: 1, dict: "amb@world_human_sunbathe@male@back@base" },
  { name: "Lying 4", anim: "base", duration: 12000000, animFlag: 1, dict: "amb@world_human_sunbathe@female@back@base" },
  { name: "Lying 5", anim: "idle_c", duration: 12000000, animFlag: 1, dict: "timetable@tracy@sleep@" },
  { name: "Sleeping", anim: "base", duration: 12000000, animFlag: 1, dict: "amb@world_human_bum_slumped@male@laying_on_right_side@base" },
  { name: "Crawling (Injured)", anim: "front_loop", duration: 12000000, animFlag: 1, dict: "move_injured_ground" },
  { name: "Lying (Injured)", anim: "idle_a", duration: 12000000, animFlag: 1, dict: "random@dealgonewrong" },
  { name: "Unconscious (Stomach)", anim: "drunk_loop", duration: 12000000, animFlag: 1, dict: "missarmenian2" },
  { name: "Unconscious (Side)", anim: "base", duration: 12000000, animFlag: 1, dict: "amb@world_human_bum_slumped@male@laying_on_left_side@base" },
  { name: "Unconscious (Back)", anim: "corpse_search_exit_ped", duration: 12000000, animFlag: 1, dict: "missarmenian2" },
  { name: "Unconscious (Back 2)", anim: "cpr_pumpchest_idle", duration: 12000000, animFlag: 1, dict: "mini@cpr@char_b@cpr_def" }
];

export const Sit = [
  { name: "Kneeling", anim: "base", duration: 12000000, animFlag: 1, dict: "amb@medic@standing@kneel@base" },
  { name: "Kneeling 2", anim: "idle_a", duration: 12000000, animFlag: 1, dict: "amb@world_human_bum_wash@male@low@idle_a" },
  { name: "Squatting", anim: "base", duration: 12000000, animFlag: 1, dict: "amb@medic@standing@tendtodead@base" },
  { name: "Squatting 2", anim: "idle", duration: 12000000, animFlag: 1, dict: "rcmextreme3" },
  { name: "Sitting (Ground)", anim: "sit_phone_phoneputdown_idle_nowork", duration: 12000000, animFlag: 1, dict: "anim@amb@business@bgen@bgen_no_work@" },
  { name: "Sitting 2 (Ground)", anim: "barry_3_sit_loop", duration: 12000000, animFlag: 1, dict: "rcm_barry3" },
  { name: "Sitting 3 (Ground)", anim: "world_human_picnic_male_lo_res_base", duration: 12000000, animFlag: 1, dict: "amb@lo_res_idles@" },
  { name: "Sitting 4 (Ground)", anim: "idle_a", duration: 12000000, animFlag: 1, dict: "amb@world_human_picnic@male@idle_a" },
  { name: "Sitting 5 (Ground)", anim: "idle_a", duration: 12000000, animFlag: 1, dict: "amb@world_human_picnic@female@idle_a" },
  { name: "Sitting 6 (Ground)", anim: "owner_idle", duration: 12000000, animFlag: 1, dict: "anim@heists@fleeca_bank@ig_7_jetski_owner" },
  { name: "Sitting 7 (Ground)", anim: "idle_a", duration: 12000000, animFlag: 1, dict: "amb@world_human_stupor@male@idle_a" },
  { name: "Sitting (Stressed)", anim: "lowalone_base_laz", duration: 12000000, animFlag: 1, dict: "anim@amb@nightclub@lazlow@lo_alone@" },
  { name: "Sitting (Sad)", anim: "sit_phone_phoneputdown_sleeping-noworkfemale", duration: 12000000, animFlag: 1, dict: "anim@business@bgen@bgen_no_work@" },
  { name: "Sitting (Fear)", anim: "hit_loop_ped_b", duration: 12000000, animFlag: 1, dict: "anim@heists@ornate_bank@hostages@hit" },
  { name: "Sitting (Fear 2)", anim: "flinch_loop", duration: 12000000, animFlag: 1, dict: "anim@heists@ornate_bank@hostages@ped_c@" },
  { name: "Sitting (Fear 3)", anim: "flinch_loop", duration: 12000000, animFlag: 1, dict: "anim@heists@ornate_bank@hostages@ped_e@" },
  { name: "Sitting (Smoking)", anim: "jimmy@_smoking_idle_03", duration: 12000000, animFlag: 1, dict: "anim_heist@arcade_combined@" },
  { name: "Sitting (Drunk)", anim: "base", duration: 12000000, animFlag: 1, dict: "timetable@amanda@drunk@base" },
  { name: "Sitting (Chair)", anim: "idle", duration: 12000000, animFlag: 1, dict: "switch@michael@sitting" },
  { name: "Sitting (Chair, Smoking)", anim: "blunt_idle_b", duration: 12000000, animFlag: 1, dict: "anim@amb@nightclub@smoking@" },
  { name: "Sitting (Chair, Leaning Forward)", anim: "base", duration: 12000000, animFlag: 1, dict: "timetable@ron@ig_3_couch" },
  { name: "Sitting (Chair, Leaned Back)", anim: "ig_2_alt1_base", duration: 12000000, animFlag: 1, dict: "timetable@ron@ron_ig_2_alt1" },
  { name: "Sitting (Chair, Masculine)", anim: "ig_5_p3_base", duration: 12000000, animFlag: 1, dict: "timetable@ron@ig_5_p3" },
  { name: "Sitting (Chair, Feminine)", anim: "base_amanda", duration: 12000000, animFlag: 1, dict: "timetable@reunited@ig_10" },
  { name: "Sitting (Sofa)", anim: "base", duration: 12000000, animFlag: 1, dict: "timetable@maid@couch@" }
];

export const Sports = [
  { name: "Warm Up", anim: "idle_e", duration: 12000000, animFlag: 1, dict: "mini@triathlon" },
  { name: "Warm Up 2", anim: "idle_f", duration: 12000000, animFlag: 1, dict: "mini@triathlon" },
  { name: "Warm Up 3", anim: "idle_d", duration: 12000000, animFlag: 1, dict: "mini@triathlon" },
  { name: "Jumping Jacks", anim: "jimmy_getknocked", duration: 12000000, animFlag: 1, dict: "timetable@reunited@ig_2" },
  { name: "Sit Up", anim: "idle_a", duration: 12000000, animFlag: 1, dict: "amb@world_human_sit_ups@male@idle_a" },
  { name: "Push-ups", anim: "idle_d", duration: 12000000, animFlag: 1, dict: "amb@world_human_push_ups@male@idle_a" },
  { name: "Jogging in Place", anim: "idle_a", duration: 12000000, animFlag: 1, dict: "amb@world_human_jog_standing@male@idle_a" },
  { name: "Yoga", anim: "idle_e", duration: 12000000, animFlag: 1, dict: "rcmfanatic1maryann_stretchidle_b" },
  { name: "Yoga 2", anim: "base_c", duration: 12000000, animFlag: 1, dict: "amb@world_human_yoga@female@base" },
  { name: "Yoga 3", anim: "base_a", duration: 12000000, animFlag: 1, dict: "amb@world_human_yoga@female@base" },
  { name: "Flexing", anim: "amb_world_human_muscle_flex_arms_in_front_base", duration: 12000000, animFlag: 1, dict: "anim@amb@nightclub@peds@" },
  { name: "Out of Breath", anim: "out_of_breath", duration: 12000000, animFlag: 1, dict: "re@construction" }
];

export const standingleaning = [
  { name: "Leaning", anim: "idle_a", duration: 12000000, animFlag: 1, dict: "amb@world_human_leaning@female@wall@back@holding_elbow@idle_a" },
  { name: "Leaning 2", anim: "idle_a", duration: 12000000, animFlag: 1, dict: "amb@world_human_leaning@male@wall@back@foot_up@idle_a" },
  { name: "Phone (Leaning)", anim: "amb_world_human_leaning_male_wall_back_mobile_idle_a", duration: 12000000, animFlag: 1, dict: "anim@amb@nightclub@peds@" },
  { name: "Smoking (Leaning)", anim: "idle_c", duration: 12000000, animFlag: 1, dict: "amb@world_human_leaning@male@wall@back@smoking@idle_a" },
  { name: "Smoking", anim: "idle_b", duration: 12000000, animFlag: 49, dict: "amb@world_human_smoking@female@idle_a" },
  { name: "Smoking 2", anim: "idle_c", duration: 12000000, animFlag: 49, dict: "amb@world_human_smoking@male@male_a@idle_a" },
  { name: "Smoking 3", anim: "idle_a", duration: 12000000, animFlag: 49, dict: "amb@world_human_aa_smoke@male@idle_a" },
  { name: "Joint Smoking", anim: "smoke_idle", duration: 12000000, animFlag: 49, dict: "timetable@gardener@smoking_joint" },
  { name: "Inspecting", anim: "idle_a", duration: 12000000, animFlag: 1, dict: "random@countrysiderobbery" },
  { name: "Taking Notes", anim: "amb_medic_standing_timeofdeath_base", duration: 12000000, animFlag: 49, dict: "anim@amb@nightclub@peds@" },
  { name: "Texting", anim: "amb_world_human_stand_mobile_male_text_idle_a", duration: 12000000, animFlag: 49, dict: "anim@amb@nightclub@peds@" },
  { name: "Texting 2", anim: "amb_world_human_stand_mobile_male_text_idle_b", duration: 12000000, animFlag: 49, dict: "anim@amb@nightclub@peds@" },
  { name: "Crossed Arms (Leaning)", anim: "stand_phone_phoneputdown_idle_nowork", duration: 12000000, animFlag: 1, dict: "anim@amb@business@bgen@bgen_no_work@" },
  { name: "Crossed Arms", anim: "single_team_loop_boss", duration: 12000000, animFlag: 49, dict: "anim@heists@heist_corona@single_team" },
  { name: "Crossed Arms 2", anim: "idle_a", duration: 12000000, animFlag: 49, dict: "amb@world_human_hang_out_street@female_arms_crossed@idle_a" },
  { name: "Crossed Arms 3", anim: "rcmme_amanda1_stand_loop_cop", duration: 12000000, animFlag: 49, dict: "anim@amb@nightclub@peds@" },
  { name: "Crossed Arms 4", anim: "_car_b_lookout", duration: 12000000, animFlag: 49, dict: "random@street_race" },
  { name: "Crossed Arms 5", anim: "_idle", duration: 12000000, animFlag: 49, dict: "random@shop_gunstore" },
  { name: "Hands on Hips", anim: "idle_a", duration: 12000000, animFlag: 49, dict: "amb@world_human_hang_out_street@female_hold_arm@idle_a" },
  { name: "Hands on Hips 2", anim: "base_idle", duration: 12000000, animFlag: 49, dict: "friends@fra@ig_1" },
  { name: "Hands on Hips (Front)", anim: "amb_world_human_stand_guard_male_base", duration: 12000000, animFlag: 49, dict: "anim@amb@nightclub@peds@" },
  { name: "Hands on Hips 2 (Front)", anim: "base", duration: 12000000, animFlag: 49, dict: "rcmnigel1a" },
  { name: "Hands Behind Back", anim: "base_a_m_y_vinewood_01", duration: 12000000, animFlag: 49, dict: "anim@amb@world_human_valet@formal_right@base@" },
  { name: "Hands on Hips 3", anim: "_idle_a", duration: 12000000, animFlag: 49, dict: "random@shop_tattoo" },
  { name: "Hands on Hips 4", anim: "ig_3_base_tracy", duration: 12000000, animFlag: 49, dict: "timetable@amanda@ig_3" },
  { name: "Hands on Hips 5", anim: "keeper_base", duration: 12000000, animFlag: 49, dict: "misshair_shop@hair_dressers" },
  { name: "Checking Mirror", anim: "try_trousers_neutral_a", duration: 12000000, animFlag: 1, dict: "mp_clothing@female@trousers" },
  { name: "Checking Mirror 2", anim: "try_shirt_positive_a", duration: 12000000, animFlag: 1, dict: "mp_clothing@female@shirt" },
  { name: "Checking Mirror 3", anim: "try_shoes_positive_a", duration: 12000000, animFlag: 1, dict: "mp_clothing@female@shoes" },
  { name: "Leaning Sideways (Wall)", anim: "packer_idle_1_trevor", duration: 12000000, animFlag: 1, dict: "misscarstealfinale" },
  { name: "Leaning Sideways (Bar)", anim: "idle_a", duration: 12000000, animFlag: 1, dict: "timetable@mime@01_gc" },
  { name: "Leaning Sideways (Bar 2)", anim: "waitloop_lamar", duration: 12000000, animFlag: 1, dict: "misscarstealfinalecar_5_ig_1" },
  { name: "Resting on Fence", anim: "idle_c", duration: 12000000, animFlag: 1, dict: "amb@world_human_bum_shopping_cart@male@idle_a" },
  { name: "Resting on Fence 2", anim: "clubvip_base_laz", duration: 12000000, animFlag: 1, dict: "anim@amb@nightclub@lazlow@ig1_vip@" },
  { name: "Resting on Bar", anim: "idle_a_bartender", duration: 12000000, animFlag: 1, dict: "anim@amb@clubhouse@bar@drink@idle_a" },
  { name: "Resting on Bar 2", anim: "idle_a_player_one", duration: 12000000, animFlag: 1, dict: "anim@mp_ferris_wheel" },
  { name: "Resting on Bar 3", anim: "idle_a_player_two", duration: 120000001, animFlag: 1, dict: "anim@mp_ferris_wheel" }
];

export const Actions = [
  { name: "Thumbs Up", anim: "idle_a", duration: 12000000, animFlag: 49, dict: "anim@mp_player_intselfiethumbs_up" },
  { name: "Thumbs Up 2", anim: "idle_a", duration: 12000000, animFlag: 49, dict: "anim@mp_player_intupperthumbs_up" },
  { name: "Thinking", anim: "b_think", duration: 2000, animFlag: 49, dict: "mp_cp_welcome_tutthink" },
  { name: "Thinking 2", anim: "rehearsal_base_idle_director", duration: 12000000, animFlag: 49, dict: "misscarsteal4@aliens" },
  { name: "Confused", anim: "gesture_shrug_hard", duration: 600, animFlag: 49, dict: "gestures@f@standing@casual" },
  { name: "Confused 2", anim: "gesture_shrug_hard", duration: 700, animFlag: 49, dict: "gestures@m@standing@casual" },
  { name: "Peace", anim: "mp_player_int_peace_sign", duration: 12000000, animFlag: 49, dict: "mp_player_int_upperpeace_sign" },
  { name: "Hitchhiking", anim: "idle_f", duration: 12000000, animFlag: 49, dict: "random@hitch_lift" },
  { name: "Blow Kiss", anim: "exit", duration: 900, animFlag: 49, dict: "anim@mp_player_intselfieblow_kiss" },
  { name: "Repairing (Engine)", anim: "fixing_a_ped", duration: 12000000, animFlag: 1, dict: "mini@repair" },
  { name: "Repairing (Squatting)", anim: "machinic_loop_mechandplayer", duration: 12000000, animFlag: 1, dict: "anim@amb@clubhouse@tutorial@bkr_tut_ig3@" },
  { name: "Repairing (Under Car)", anim: "idle_b", duration: 12000000, animFlag: 1, dict: "amb@world_human_vehicle_mechanic@male@idle_a" },
  { name: "Repairing (Engine 2)", anim: "prop_cuff_keys_01", duration: 12000000, animFlag: 1, dict: "amb@world_human_vehicle_mechanic@male@idle_a" },
  { name: "Taking Photo", anim: "idle_a", duration: 12000000, animFlag: 49, dict: "random@paparazzi@base" },
  { name: "Taking Photo 2", anim: "base", duration: 12000000, animFlag: 49, dict: "random@paparazzi@wait" },
  { name: "Taking Photo 3", anim: "base", duration: 12000000, animFlag: 49, dict: "random@paparazzi@pap_anims" },
  { name: "Selfie", anim: "idle_a", duration: 12000000, animFlag: 49, dict: "mp_player_int_upper_selfie" },
  { name: "Selfie 2", anim: "idle_a", duration: 12000000, animFlag: 49, dict: "anim@mp_player_intupperneutral_salute" },
  { name: "Selfie 3", anim: "mp_player_int_upper_praise", duration: 12000000, animFlag: 49, dict: "mp_player_int_upper_praise" },
  { name: "Selfie 4", anim: "photo", duration: 12000000, animFlag: 49, dict: "amb@world_human_mobile_film_shocking@male@base" },
  { name: "Selfie 5", anim: "base", duration: 12000000, animFlag: 49, dict: "amb@world_human_tourist_mobile@female@base" },
  { name: "Record Video", anim: "idle_a", duration: 12000000, animFlag: 49, dict: "amb@world_human_paparazzi@male@base" },
  { name: "Record Video 2", anim: "idle_a", duration: 12000000, animFlag: 49, dict: "amb@world_human_mobile_film_shocking@male@base" },
  { name: "Record Video 3", anim: "base", duration: 12000000, animFlag: 49, dict: "random@paparazzi@pap_anims" },
  { name: "Boxing", anim: "idle_a", duration: 12000000, animFlag: 49, dict: "anim@mp_ferris_wheel" },
  { name: "Boxing 2", anim: "idle_a", duration: 12000000, animFlag: 49, dict: "amb@world_human_combat_grounded@male@idle_a" },
  { name: "Boxing 3", anim: "amb_dance_loop_male_a", duration: 12000000, animFlag: 49, dict: "anim@amb@nightclub@dancers@crowddance_facedj@" },
  { name: "Boxing 4", anim: "idle_b", duration: 12000000, animFlag: 49, dict: "anim@mp_ferris_wheel" },
  { name: "Boxing 5", anim: "idle_b", duration: 12000000, animFlag: 49, dict: "anim@mp_ferris_wheel" }
];

export const Greet = [
  { name: "Wave 1", anim: "wave_e", duration: 1600, animFlag: 49, dict: "friends@frj@ig_1" },
  { name: "Wave 2", anim: "wave_d", duration: 1300, animFlag: 49, dict: "friends@frj@ig_1" },
  { name: "Wave 3",  anim: "wave_b", duration: 3900,  animFlag: 49, dict: "friends@frj@ig_1" },
  { name: "Hug", anim: "kisses_guy_b", duration: 5400, animFlag: 1, dict: "mp_ped_interaction" },
  { name: "Hug 2", anim: "kisses_guy_a", duration: 5300, animFlag: 1, dict: "mp_ped_interaction" },
  { name: "Whistle", anim: "hail_taxi", duration: 710, animFlag: 49, dict: "taxi_hail" },
  { name: "Whistle 2", anim: "hailing_whistle_waive_a", duration: 1500, animFlag: 49, dict: "rcmnigel1c" },
  { name: "Salute (Right Hand)", anim: "idle_a", duration: 12000000, animFlag: 49, dict: "anim@mp_player_intincarsalutestd@ds@" },
  { name: "Salute (Sideways)", anim: "idle_a", duration: 12000000, animFlag: 49, dict: "anim@mp_player_intuppersalute" },
  { name: "Gang Sign", anim: "mp_player_int_gang_sign_a", duration: 12000000, animFlag: 49, dict: "mp_player_int_uppergang_sign_a" },
  { name: "Gang Sign 2", anim: "mp_player_int_gang_sign_b", duration: 12000000, animFlag: 49, dict: "mp_player_int_uppergang_sign_b" }  
];

export const Aggressive = [
  { name: "Show Off", anim: "bring_it_on", duration: 3000, animFlag: 49, dict: "misscommon@response" },
  { name: "Discuss", anim: "actor_berating_loop", duration: 12000000, animFlag: 49, dict: "misscarsteal4@actor" },
  { name: "Chicken", anim: "wakeup", duration: 3500, animFlag: 1, dict: "random@peyote@chicken" },
  { name: "F*ck You", anim: "screw_you", duration: 2000, animFlag: 49, dict: "misscommon@response" },
  { name: "Middle Finger (One Finger)", anim: "idle_a", duration: 12000000, animFlag: 49, dict: "anim@mp_player_intselfiethe_bird" },
  { name: "Middle Finger (Two Fingers)", anim: "idle_a_fp", duration: 12000000, animFlag: 49, dict: "anim@mp_player_intupperfinger" },
  { name: "Middle Finger (One Finger Aggressivee)", anim: "flip_off_a_1st", duration: 4400, animFlag: 49, dict: "anim@arena@celeb@podium@no_prop@" },
  { name: "Middle Finger (Two Fingers Aggressivee)", anim: "flip_off_c_1st",  duration: 5000, animFlag: 49, dict: "anim@arena@celeb@podium@no_prop@" },
  { name: "Knuckle Crack", anim: "knuckle_crunch", duration: 4000, animFlag: 49, dict: "anim@mp_player_intcelebrationfemale@knuckle_crunch" }
];